//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ErysDownloader
{
    public class Direct : IChannel
    {
        public Uri Url { get; set; }
        public ITransport Transport { get; set; }

        public virtual Response SendRequest(Request request)
        {

            request.IsConnected = true;

            request.RequestHeader["get"] = "GET " + request.Url.PathAndQuery + " HTTP/1.1";

            return Transport.ExecuteRequest(request);

        }

    }
}
