//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ErysDownloader
{
    public interface IProxyClient
    {
        int Port { get; set; }

        string Host { get; set; }

        Credencial Credencial { get; set; }

        void Connect(System.IO.Stream session, IEnumerable<string> commandLine);

    }

}