//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;


namespace ErysDownloader
{
    public interface ITransport
    {
        Response ExecuteRequest(Request request);

    }
}
