//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ErysDownloader
{
    public class Response
    {
        public virtual string Content
        {
            get;
            set;
        }

        public virtual ResponseHeaders Headers
        {
            get;
            set;
        }

    }
}

