//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace ErysDownloader
{

    public class SocketDownloader : HttpRequest
    {
        public SocketDownloader()
        {
            Channel = new Direct();
            Channel.Transport = new Socket.HttpProtocol();
        }

        public SocketDownloader(IChannel channel)
        {
            Channel = channel;
            Channel.Transport = new Socket.HttpProtocol();
            if (channel is IProxyClient)
            {
                var destination = ((IProxyClient)Channel);
                Channel.Url = new Uri(string.Format("http://{0}:{1}", destination.Host, destination.Port));
            }
        }

    }

}



